### ISSUE TITLE
XML File Saving

### ISSUE THREAD

**Issue by Thegvoge** [Yetet/SignOutManager#6]
We need to save this XML file to a place that it can continually write to and also where the teacher can easily access

**Comment by Yetet** [comment]
On first time run, prompt a popup with a DocumentViewer and save it to the selected directory.

**Comment by Yetet** [comment]
Idk if this was fixed or not but it's fine

**Comment by Thegvoge** [comment]
I can't change the xml file saving location so I can't try and change how
the program starts and writes
